language: node_js
node_js:
  - "7"
sudo: true
dist: trusty

branches:
  only:
  - master

before_script:
 - sudo apt-get update

script:
  - cd client
  - npm install
  - npm test
  - npm install codecov -g

after_success:
  - codecov --token=c76c9a92-e521-44c6-80fb-ce20d5deb9f8